FROM python:3.13-slim AS build
WORKDIR /code
COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install --prefix=/install -r requirements.txt
COPY . /code/

FROM python:3.13-slim AS production
WORKDIR /code
COPY --from=build /install /usr/local
COPY --from=build /code /code
EXPOSE 8000
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "myproject.asgi:application"]
