FROM python:3.10-slim AS build
WORKDIR /code
COPY requirements.txt /code/
RUN pip install --upgrade pip setuptools==78.1.1
RUN pip install -r requirements.txt
COPY . /code/

FROM python:3.10-slim AS production
WORKDIR /code
COPY --from=build /usr/local /usr/local
COPY --from=build /code /code
EXPOSE 8000
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "myproject.asgi:application"]
