version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    image: taha2samy/mybrocker:4.0.6
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 myproject.asgi:application"
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
