# Generated by Django 5.2.6 on 2025-09-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('max_connections', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=5)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brocker.broker')),
            ],
        ),
    ]
