# Generated by Django 5.2.6 on 2025-09-22 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broker',
            new_name='BrokerTokens',
        ),
        migrations.RemoveField(
            model_name='brokerpermission',
            name='topic',
        ),
        migrations.AddField(
            model_name='brokerpermission',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brocker.brokertags'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brokerpermission',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('readwrite', 'ReadWrite')], max_length=11),
        ),
        migrations.AlterField(
            model_name='brokertags',
            name='prefix',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='brokerpermission',
            constraint=models.UniqueConstraint(fields=('broker', 'tag'), name='unique_broker_tag'),
        ),
    ]
