# Generated by Django 5.2.6 on 2025-09-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocker', '0002_rename_broker_brokertokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokertokens',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
