# Generated by Django 5.2.6 on 2025-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brocker', '0003_alter_brokertokens_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokertokens',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
